### PR TITLE
Updated the UI for mobile view

### LINKED ISSUE #13: Update UI arrangement on mobile screen
Currently, on mobile screens, the order of the UI is Ludo board > Heading > Control. Update the order to be Heading > Ludo board > Control on mobile screens.
image

If you have any more questions or need more clarity on this issue, endeavour to join the StarkLudo contributors channel (https://t.me/+hnjQooODZOA2M2Rk) on Telegram and the project leads will be there to help.

### PR DESCRIPTION
**Pull request by PoulavBhowmick03**
## Overview

This PR introduces mobile responsiveness for the StarkLudo game interface. The changes ensure that the Ludo board and controls are well-positioned and accessible on smaller screens while maintaining the existing layout on larger screens.

## Changes Made

1. **Mobile Layout**:
   - The header is now stacked above the Ludo board to optimize space usage on smaller screens.
   - Controls are moved below the Ludo board when viewed on mobile devices.
   - Adjusted margins, padding, and font sizes to ensure that the UI elements are appropriately scaled for touch devices.

2. **CSS Enhancements**:
   - Added media queries to handle screen size detection and apply the appropriate styles.
   - Updated flexbox and grid settings to adapt the layout based on the screen width.

3. **Tested Responsiveness**:
   - Ensured the layout works seamlessly across various screen sizes, including tablets and mobile devices.
   - Verified that no functionality is broken during the transition from desktop to mobile view.

### Before
image
#### Mobile View
image
## How to Test

1. Pull the latest changes from this branch.
2. Open the StarkLudo interface on different screen sizes (desktop, tablet, and mobile).
3. Verify that the layout adapts correctly, with the header above the Ludo board on smaller screens.
4. Ensure all buttons and controls are functional and easy to use on touch devices.

## Related Issues

- Resolves #13
---

Let me know if you have any questions or need further adjustments!

### CODE REVIEW

**Comment by vibenedict** [comment]
Hi @PoulavBhowmick03 
Great job

The UI is now ordered properly on mobile view. However, I noticed you did not maintain the previous order of the layout on desktop view. i.e ludo board on left, and controls on the right.
image

Please can you fix that and update your PR ASAP?

**Comment by vibenedict** [comment]
Hi @PoulavBhowmick03, any update on this?

**Comment by PoulavBhowmick03** [comment]
I am having some issues in building the contract to test the changes. I will definitely get it done by tomorrow morning at earliest

**Comment by ibsule** [comment]
Hi @PoulavBhowmick03, any progress on this?

**Comment by PoulavBhowmick03** [comment]
> Hi @PoulavBhowmick03, any progress on this?
> 

Yes I was having setup issues, as discussed with you yesterday on Telegram. I'll get it done today definitely

**Comment by princeibs** [comment]
> > Hi @PoulavBhowmick03, any progress on this?
> 
> Yes I was having setup issues, as discussed with you yesterday on Telegram. I'll get it done today definitely

**Pull request closed without merging**
