### PR TITLE
Feat: Gameboard grid implementation

### LINKED ISSUE #131: Game Board Grid Implementation with Consideration for Other Board Provided Board Skins for Easy Customization.
### Description

Create the central game board using a grid layout with interactive tiles. Ensure that the Ludo tiles can move uniformly and parametrically on the board. The React component should accept props that make the movement of the Ludo tiles deterministic, in relation to the board component and its tiles:

- [ ] Implement grid structure
- [ ] Implement tile hover states
- [ ] Make sure the tile can move determinstically like the description stated add transition to the movement
- [ ] Add movement indicators
- [ ] Mark sure it is responsive given that it could be a child component to a parent. Make sure there are adjustable breakpoint fpr the board component.

**Technical Requirements:**
- Use Tailwind Grid for layout to ensure consistency
- Implement tile components as reusable React components
- Add proper spacing and borders
- Match the design colors for different tile types
- Ensure the grid scales properly on all screen sizes without causing overflow
---

### PR DESCRIPTION
**Pull request by josephchimebuka**
closes #131

### CODE REVIEW

**Review by ibsule — CHANGES_REQUESTED** [review]
CI is failing

**Comment by ibsule** [comment]
@josephchimebuka any update on this?

**Comment by josephchimebuka** [comment]
Yes ser there's... Give me today and I'll send it

**Review by ibsule — CHANGES_REQUESTED** [review]
Can you resolve conflicts and ensure the CI is passing?

**Comment by Nityam573** [comment]
Can I try this if it is failing

**Comment by josephchimebuka** [comment]
> Can you resolve conflicts and ensure the CI is passing?

Yes ser I will resolve it right now... I did it before some new PRs were merged

**Comment by josephchimebuka** [comment]
@princeibs there are no branch conflicts now ser... And I ran lint on local no errors

**Comment by ibsule** [comment]
image
Still failing

**Comment by josephchimebuka** [comment]
Hello @princeibs,...I’ve fixed the errors locally, but it seems I need permission to view the CI pipeline, or it needs to be approved by the maintainer. Could you help me check it?

**Comment by josephchimebuka** [comment]
Hello @princeibs,...I’ve fixed the errors locally,it should pass CI now

**Pull request merged**
