### PR TITLE
feat: implement avatar section

### LINKED ISSUE #118: Implement Avatar Selection Interface
## Description
Create an avatar selection interface that allows players to choose their in-game character from a set of pixel art avatars. The interface should appear when clicking the "Your avatar" button in the game menu.

### Toggle Interface
- [ ] Make sure to update the gamestate context provider of you implementation 
- [ ] Implement toggle functionality for the "Your avatar" button
- [ ] Create smooth transition for opening/closing the avatar selection panel
- [ ] Add close button in the top-right corner

### ETA
This issue is expected to be completed within 2 days or being assigned. Failure to create a pull request or draft pull request will lead to the contributor being unassigned

### PR DESCRIPTION
**Pull request by Akshola00**
implements avatar selection page
fixes #118

### CODE REVIEW

**Review by ibsule — CHANGES_REQUESTED** [review]
CI is failing

**Review by ibsule — CHANGES_REQUESTED** [review]
CI is still failing

**Comment by vibenedict** [comment]
Any update on this? @Akshola00

**Comment by Akshola00** [comment]
> Any update on this? @Akshola00 

Fixing this now

**Comment by ibsule** [comment]
@Akshola00

**Comment by Akshola00** [comment]
ready for review @princeibs

**Review by ibsule — CHANGES_REQUESTED** [review]
CI is still failing with these messages: 
image

**Review by ibsule — APPROVED** [review]

**Pull request merged**
