### PR TITLE
feat: updated game board to expand to half the page

### LINKED ISSUE #12: Expand board to fit 50% of screen size
First half of the screen is dedicated to the Ludo board but currently the board only occupies a small potion of it. Your task is to expand the board to fill the remaining space left in the first half of the screen. The increased size should also respond to mobile screens.

image

If you have any more questions or need more clarity on this issue, endeavour to join the StarkLudo contributors channel (https://t.me/+hnjQooODZOA2M2Rk) on Telegram and the project leads will be there to help.

### PR DESCRIPTION
**Pull request by Ayoazeez26**
Fixes #12

### CODE REVIEW

**Comment by vibenedict** [comment]
Great job @Ayoazeez26 
However, the pieces on the board does not well positioned in their various homes and when they start moving, they don't move along the tile nodes of the board.
Please can you fix that and create a PR ASAP?
image

**Comment by Ayoazeez26** [comment]
Sure @vibenedict I’ll fix and revert

**Comment by Ayoazeez26** [comment]
@vibenedict please check and let me know if it's good to go

**Review by vibenedict — APPROVED** [review]
LGTM

**Pull request merged**
