### PR TITLE
feat: added new design of color selection system

### LINKED ISSUE #116: Color Selection System
image

### Description
Create a color selection interface with gem-styled options for player colors.

#### Requirements
- [ ] Make sure to update the game state context provider of your implementation `game-hook.tsx`
- [ ] Implement four color options:
  - Blue gem
  - Green gem
  - Orange gem
  - Red gem
- [ ] Add hover effects for gems
- [ ] Show selected state
- [ ] Implement selection confirmation
- [ ] Add close button functionality

#### Technical Notes
- Use SVG for gem graphics
- Implement proper color accessibility like keyboard selection
- Add subtle animations for selection
---

### ETA
This issue is expected to be completed within 2 days or being assigned. Failure to create a pull request or draft pull request will lead to the contributor being unassigned

### PR DESCRIPTION
**Pull request by melnikga**
## Description

A page with a new color selection design has been added. The color can also be selected from the keyboard using the keys r, g, b, o

## Related Issue(s) #116

Closes #116
## Checklist:

- [x] Read the [contributing docs](../CONTRIBUTING.md) (if this is your first contribution)
- [x] Verified this is not a duplicate of any [existing pull request](https://github.com/sivicstudio/starkludo/pulls)

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [x] Documented the changes in code (API docs will be generated automatically)

### CODE REVIEW

**Review by ibsule — CHANGES_REQUESTED** [review]
CI is failing

**Comment by melnikga** [comment]
@princeibs i'll fix that tonight

**Review by ibsule — CHANGES_REQUESTED** [review]
Please resolve conflicts

**Comment by melnikga** [comment]
@princeibs I resolved conflicts

**Review by ibsule — APPROVED** [review]

**Pull request merged**
