### PR TITLE
Implement join game function

### LINKED ISSUE #80: Create the "Join game" function
**Description**
- The join game function should be added to game actions
- The function should allow a player to join a pending game using the game ID.
 - It should take in the game Id and the player color and add the player's username to the game state

**Action Items**
- Create the join game function
- Create the corresponding test cases for the join game function

### PR DESCRIPTION
**Pull request by Benjtalkshow**
closes #80 
## 1 - join game function
Implemented a join game function which checks if the game with the given game_id is in a waiting state. Then adds the player's username to the appropriate color slot in the game state and If all required players have joined, it changes the game status from "Waiting" to "Ongoing".

## 2 - join game function test
Implemented test cases for the join game function which includes:
1. Verifying that players can successfully join a game using different colors.
2. Checks that the player's username is correctly added to the game state.
3. Ensures the game status remains "Waiting" while players are joining.
4. Confirms the game status changes to "Ongoing" when all required players have joined.

### CODE REVIEW

**Comment by ibsule** [comment]
@Benjtalkshow are you having any challenge completing this?
You can also ping the StarkLudo Contributors channel on Telegram if you need more clarity on this issue.

**Comment by Benjtalkshow** [comment]
> @Benjtalkshow are you having any challenge completing this? You can also ping the StarkLudo Contributors channel on Telegram if you need more clarity on this issue.

Yea just chatted you few min ago with handle Kitch. I am working on it.

**Review by ibsule — CHANGES_REQUESTED** [review]
image
- Please fix failing contract CI and client CI

**Comment by Benjtalkshow** [comment]
@princeibs 
Will make my final PR soon sir

**Comment by ibsule** [comment]
Please fix failing CI

**Comment by Benjtalkshow** [comment]
@princeibs 
I have updated my PR

**Pull request merged**
