### PR TITLE
refac: add figma link

### LINKED ISSUE #20: Design new Ludo boards
Design 2 new boards for StarkLudo on Figma. You can make research about various boards design and variation of the Ludo game. If you can come up with more than 2 boards, the extra effort will be accounted for.

If you have any more questions or need more clarity on this issue, endeavour to join the StarkLudo contributors channel (https://t.me/+hnjQooODZOA2M2Rk) on Telegram and the project leads will be there to help.

### PR DESCRIPTION
**Pull request by Calebux**
Closes #20 

Added the figma link
Designed two ludo boards

### CODE REVIEW

**Review by vibenedict — CHANGES_REQUESTED** [review]
Please add your design link to [FIGMA_DESIGNS.md](https://github.com/sivicstudio/starkludo/blob/dev/assets/FIGMA_DESIGNS.md)

**Comment by Calebux** [comment]
> Please add your design link to [FIGMA_DESIGNS.md](https://github.com/sivicstudio/starkludo/blob/dev/assets/FIGMA_DESIGNS.md)

it's in the Readme

**Comment by vibenedict** [comment]
> > Please add your design link to [FIGMA_DESIGNS.md](https://github.com/sivicstudio/starkludo/blob/dev/assets/FIGMA_DESIGNS.md)
> 
> it's in the Readme

Please add it to FIGMA_DESIGNS.md file

**Comment by Calebux** [comment]
> > > Please add your design link to [FIGMA_DESIGNS.md](https://github.com/sivicstudio/starkludo/blob/dev/assets/FIGMA_DESIGNS.md)
> > 
> > 
> > it's in the Readme
> 
> Please add it to FIGMA_DESIGNS.md file

Done

**Review by vibenedict — APPROVED** [review]
LGTM

**Pull request merged**
