### PR TITLE
feat: added game settings screen

### LINKED ISSUE #117: Game Settings Panel Implementation
image

### Description
Implement a settings panel with audio controls, difficulty selection, and background customization options.

#### Requirements
- [ ] Make sure to update the game state context provider of you implementation `game-hook.tsx`
- [ ] Create sound volume slider with proper icons and 10-step indicator
- [ ] Implement music volume slider with note icons and 10-step indicator
- [ ] Add difficulty selection buttons:
  - Beginner (default)
  - Experienced
  - Professional
- [ ] Add background customization option
- [ ] Implement proper state management for settings
- [ ] Add close button functionality

### ETA
This issue is expected to be completed within 2 days or being assigned. Failure to create a pull request or draft pull request will lead to the contributor being unassigned

### PR DESCRIPTION
**Pull request by abdegenius**
## Description

New game panel UI was implemented, react-router-dom was installed and configured no existing code was affected, to check update navigate to /settings to view new screen design!

## Related Issue(s)

Closes #117
## Checklist:

- [x] Read the [contributing docs](../CONTRIBUTING.md) (if this is your first contribution)
- [x] Verified this is not a duplicate of any [existing pull request](https://github.com/sivicstudio/starkludo/pulls)

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [x] Documented the changes in code (API docs will be generated automatically)

### CODE REVIEW

**Comment by abdegenius** [comment]
@princeibs PR made please check!

**Review by ibsule — CHANGES_REQUESTED** [review]
Please fix failing CI and conflicts.
I think you can remove `pnpm-lock.yaml` from the PR to avoid conflicts

**Comment by abdegenius** [comment]
Ok am on it

**Review by ibsule — CHANGES_REQUESTED** [review]
Please fix conflicts

**Comment by abdegenius** [comment]
Uhmmm made a fix to handle the conflict seems it didn't take effect... Will review it over again

**Pull request closed without merging**
