### PR TITLE
Adjusted CSS to fit in screen

### LINKED ISSUE #72: Make page fit 100% of screen
**Description**
Currently, the page does not fit 100% of the screen. Players have to scroll down to see the other parts of the page.

**Action items**
- Make page fit 100% of the screen it is view from.
- Take note of the warning banner at the top. The page should still fit 100% even when the banner is removed
image

### PR DESCRIPTION
**Pull request by PoulavBhowmick03**
## Description

Fixes #72 
## Related Issue(s)

Closes #72
## Checklist:

- [X] Read the [contributing docs](../CONTRIBUTING.md) (if this is your first contribution)
- [X] Verified this is not a duplicate of any [existing pull request](https://github.com/sivicstudio/starkludo/pulls)

- [X] Performed a self-review of the code
- [X] Rebased to the last commit of the target branch (or merged it into my branch)
- [X] Linked the issues which this PR resolves
- [X] Documented the changes in code (API docs will be generated automatically)
image
image
image

### CODE REVIEW

**Review by ibsule — CHANGES_REQUESTED** [review]
- Please fix failing checks 
image

**Comment by PoulavBhowmick03** [comment]
image
@princeibs Fixed it. PTAL

**Comment by ibsule** [comment]
Please fix failing CI and also resolve conflicts

**Comment by PoulavBhowmick03** [comment]
@princeibs the conflicts and tests are resolved. PTAL and merge it under ODHACK 8

**Review by ibsule — CHANGES_REQUESTED** [review]
image
Can you revert to the initial layout?
And also, the game doesn't fit my screen. I had to scroll down to see other parts of it.

**Pull request closed without merging**
